

BEGIN TRANSACTION;
UPDATE dbo.DEPT 
 SET DNAME = 'TALENTO HUMANO'
 WHERE DEPTNO = 10;
 select * from dbo.dept WHERE DEPTNO IN (10, 20, 30, 40, 50);
 COMMIT;

 BEGIN TRANSACTION;
 INSERT INTO DBO.DEPT VALUES (80,'VENTA','CUENCA');
   --ROLLBACK;
 COMMIT;