USE PRUEBAS;
select * from dbo.dept;
SELECT * FROM DBO.EMP;

BEGIN TRANSACTION;
UPDATE dbo.DEPT 
 SET DNAME = 'SISTEMAS'
 WHERE DEPTNO = 10;
 select * from dbo.dept;

 --ROLLBACK;
 COMMIT;
 
BEGIN TRANSACTION;
 INSERT INTO DBO.DEPT VALUES (80,'POST-VENTA','MANTA');
  --ROLLBACK;
 COMMIT;